apps/sigma_metas/urls.py
from django.contrib import admin
from django.urls import path
from apps.sigma_metas.views.accion import *
from apps.sigma_metas.views.accionestrategica import *
from apps.sigma_metas.views.areapriorizada import *
from apps.sigma_metas.views.indicador import *
from apps.sigma_metas.views.meta import *
from apps.sigma_metas.views.organismo import *
from apps.sigma_metas.views.plan import *
from apps.sigma_metas.views.tarea import *
from apps.sigma_metas.views.reporte import *

app_name='sigma'

urlpatterns = [
    #accion
    path('accion/list/',AccionListView.as_view(), name='accion_list'),
    path('accion/create/',AccionCreateView.as_view(), name='accion_create'),
    path('accion/update/<int:pk>/',AccionUpdateView.as_view(), name='accion_update'),
    path('accion/delete/<int:pk>/',AccionDeleteView.as_view(), name='accion_delete'),

    # accion estrategica
    path('accion/estrategica/list/', AccionEstrategicaListView.as_view(), name='accion_estrategica_list'),
    path('accion/estrategica/create/', AccionEstrategicaCreateView.as_view(), name='accion_estrategica_create'),
    path('accion/estrategica/update/<int:pk>/', AccionEstrategicaUpdateView.as_view(), name='accion_estrategica_update'),
    path('accion/estrategica/delete/<int:pk>/', AccionEstrategicaDeleteView.as_view(), name='accion_estrategica_delete'),

    # area priorizada
    path('area/list/', AreaPriorizadaListView.as_view(), name='area_list'),
    path('area/create/', AreaPriorizadaCreateView.as_view(), name='area_create'),
    path('area/update/<int:pk>/', AreaPriorizadaUpdateView.as_view(), name='area_update'),
    path('area/delete/<int:pk>/', AreaPriorizadaDeleteView.as_view(), name='area_delete'),

    # indicador
    path('indicador/list/', IndicadorListView.as_view(), name='indicador_list'),
    path('indicador/create/', IndicadorCreateView.as_view(), name='indicador_create'),
    path('indicador/update/<int:pk>/', IndicadorUpdateView.as_view(), name='indicador_update'),
    path('indicador/delete/<int:pk>/', IndicadorDeleteView.as_view(), name='indicador_delete'),

    # meta
    path('meta/list/', MetaListView.as_view(), name='meta_list'),
    path('meta/create/', MetaCreateView.as_view(), name='meta_create'),
    path('meta/update/<int:pk>/', MetaUpdateView.as_view(), name='meta_update'),
    path('meta/delete/<int:pk>/', MetaDeleteView.as_view(), name='meta_delete'),

    # organismo
    path('organismo/list/', OrganismoListView.as_view(), name='organismo_list'),
    path('organismo/create/', OrganismoCreateView.as_view(), name='organismo_create'),
    path('organismo/update/<int:pk>/', OrganismoUpdateView.as_view(), name='organismo_update'),
    path('organismo/delete/<int:pk>/', OrganismoDeleteView.as_view(), name='organismo_delete'),

    # plan
    path('plan/list/', PlanListView.as_view(), name='plan_list'),
    path('plan/create/', PlanCreateView.as_view(), name='plan_create'),
    path('plan/update/<int:pk>/', PlanUpdateView.as_view(), name='plan_update'),
    path('plan/delete/<int:pk>/', PlanDeleteView.as_view(), name='plan_delete'),

    # tarea
    path('tarea/list/', TareaListView.as_view(), name='tarea_list'),
    path('tarea/create/', TareaCreateView.as_view(), name='tarea_create'),
    path('tarea/update/<int:pk>/', TareaUpdateView.as_view(), name='tarea_update'),
    path('tarea/delete/<int:pk>/', TareaDeleteView.as_view(), name='tarea_delete'),

    #reportes
    path('reporte/acciones/', ReporteAccion.as_view(), name='reporte_accion'),
    path('reporte/financiamiento/', Reportefinanciamiento.as_view(), name='reporte_financiamiento'),

]

sigma/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import LogoutView
from django.conf.urls.static import static
from apps.login.views import *
from apps.sigma_metas.views.index import *
from apps.sigma_metas.views.plan import PlanListView

from sigma import settings
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('apps.sigma_metas.urls')),
    path('', include('apps.user.urls')),
    path('', LoginFormView.as_view(), name='index'),
    path('index/', PlanListView.as_view(), name='index'),
    path('login/', include('apps.login.urls')),
    path('logout/', LogoutView.as_view(), name='logout'),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/sigma_metas/models.py
import datetime

from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator

Indicadores_Unidad_Medida_Choices = (
    ('dia', 'Dias'),
    ('mes', 'Meses'),
    ('ano', 'Años'),
)
Estado_Choices = (
    ('realizado', 'Realizado'),
    ('aplazado', 'Aplazado'),
    ('pendiente', 'Pendiente'),
)


class Plan(models.Model):
    nombre = models.CharField(max_length=200, verbose_name='Nombre del Plan')
    descripcion = models.TextField(max_length=500, verbose_name='Descripción del plan')
    acciones_estrategica_id = models.ManyToManyField('AccionEstrategica', verbose_name='Acción estrategica')
    tareas_id = models.ManyToManyField('Tarea', verbose_name='Tareas')

    def __str__(self):
        return self.nombre

    class Meta:
        db_table = 'TB_PLan'
        default_permissions = []
        permissions = ()
        ordering = ['-id']


class AccionEstrategica(models.Model):
    nombre = models.CharField(max_length=200, verbose_name='Nombre de la Acción Estratégica')
    descripcion = models.TextField(max_length=500, verbose_name='Descripción de la acción estratégica')

    def __str__(self):
        return self.nombre

    class Meta:
        db_table = 'TB_AccionEstrategica'
        default_permissions = []
        permissions = ()
        ordering = ['-id']


class Tarea(models.Model):
    nombre = models.CharField(max_length=200, verbose_name='Nombre de la Tarea')
    descripcion = models.TextField(max_length=500, verbose_name='Descripción de la tarea')

    def __str__(self):
        return self.nombre

    class Meta:
        db_table = 'TB_Tarea'
        default_permissions = []
        permissions = ()
        ordering = ['-id']


class Meta(models.Model):
    nombre = models.CharField(max_length=200, verbose_name='Nombre de la Meta')
    descripcion = models.TextField(max_length=500, blank = True, verbose_name='Descripción de la meta')
    indicador_id = models.ForeignKey('Indicador', on_delete=models.CASCADE, null=True, blank=True,
                                     verbose_name='Indicadores')
    acciones_estrategica_id = models.ForeignKey('AccionEstrategica', on_delete=models.CASCADE, null=True, blank=True,
                                                verbose_name='Acciones')
    organismo_id = models.ForeignKey('Organismo', on_delete=models.CASCADE, null=True, blank=True, verbose_name='Organismo')

    def __str__(self):
        return self.nombre

    class Meta:
        db_table = 'TB_Meta'
        default_permissions = []
        permissions = ()
        ordering = ['-id']


class Indicador(models.Model):
    nombre = models.CharField(max_length=200, verbose_name='Nombre del Indicador')
    descripcion = models.TextField(max_length=500, blank = True, verbose_name='Descripción del indicador')
    unidad_medida = models.CharField(max_length=200, verbose_name='U/M')

    def __str__(self):
        return self.unidad_medida

    class Meta:
        db_table = 'TB_Indicador'
        default_permissions = []
        permissions = ()
        ordering = ['-id']


class Accion(models.Model):
    nombre = models.CharField(max_length=200, verbose_name='Nombre de la Acción')
    area_id = models.ForeignKey('AreaPriorizada', on_delete=models.CASCADE, verbose_name='Áreas Priorizadas')
    organismo_id = models.ForeignKey('Organismo', on_delete=models.CASCADE, verbose_name='Organismo')
    tarea_id = models.ForeignKey('Tarea', on_delete=models.CASCADE, verbose_name='Tarea')
    presupuesto = models.DecimalField(max_digits=9, decimal_places=2, default=0,
                                      validators=[MinValueValidator(0, message='El importe debe ser positivo')],
                                      verbose_name='Presupuesto')
    financiamiento = models.DecimalField(max_digits=9, decimal_places=2, default=0,
                                         validators=[MinValueValidator(0, message='El importe debe ser positivo')],
                                         verbose_name='Financiamiento')
    fuente_financimiento = models.CharField(max_length=200, verbose_name='Fuente de financiamiento')
    estado = models.CharField(max_length=15, choices=Estado_Choices, verbose_name='Estado de la acción')
    observacion = models.CharField(max_length=500, verbose_name='Observaciones')

    def __str__(self):
        return self.nombre

    class Meta:
        db_table = 'TB_Accion'
        default_permissions = []
        permissions = ()
        ordering = ['-id']


class Organismo(models.Model):
    nombre = models.CharField(max_length=200, verbose_name='Nombre del Organismo')
    descripcion = models.TextField(max_length=500, blank = True, verbose_name='Descripción del organismo')

    def __str__(self):
        return self.nombre

    class Meta:
        db_table = 'TB_Organismo'
        default_permissions = []
        permissions = ()
        ordering = ['-id']


class AreaPriorizada(models.Model):
    nombre = models.CharField(max_length=200, verbose_name='Nombre del Área')
    descripcion = models.TextField(max_length=500, verbose_name='Descripción del área')

    def __str__(self):
        return self.nombre

    class Meta:
        db_table = 'TB_Area'
        default_permissions = []
        permissions = ()
        ordering = ['-id']

apps/sigma_metas/views.py
from django.shortcuts import render

# Create your views here.

apps/sigma_metas/views/accion.py
from django.urls import reverse_lazy
from django.views.generic import *

from apps.mixins import JefePermissionRequiredMixin
from apps.sigma_metas.forms import AccionForm
from apps.sigma_metas.models import Accion
from django.contrib.auth.mixins import LoginRequiredMixin

class AccionListView(LoginRequiredMixin,ListView):
    model = Accion
    template_name = 'accion/accion_list.html'
    queryset = Accion.objects.all()
    success_url = reverse_lazy('sigma:accion_list')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['create_url'] = reverse_lazy('sigma:accion_create')
        context['entity'] = 'Accion'
        context['title'] = 'Listado de las acciones'
        return context


class AccionCreateView(JefePermissionRequiredMixin,LoginRequiredMixin,CreateView):
    model = Accion
    template_name = 'form.html'
    form_class = AccionForm
    success_url = reverse_lazy('sigma:accion_list')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['create_url'] = reverse_lazy('sigma:accion_create')
        context['entity'] = 'Accion'
        context['title'] = 'Crear una accion'
        context['list_url'] = self.success_url
        return context


class AccionUpdateView(JefePermissionRequiredMixin,LoginRequiredMixin,UpdateView):
    model = Accion
    template_name = 'form.html'
    form_class = AccionForm
    success_url = reverse_lazy('sigma:accion_list')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['create_url'] = reverse_lazy('sigma:accion_create')
        context['entity'] = 'Accion'
        context['title'] = 'Actualizar accion'
        context['list_url'] = self.success_url
        return context


class AccionDeleteView(JefePermissionRequiredMixin,LoginRequiredMixin,DeleteView):
    model = Accion
    template_name = 'delete.html'
    success_url = reverse_lazy('sigma:accion_list')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['create_url'] = reverse_lazy('sigma:accion_create')
        context['entity'] = 'Accion'
        context['title'] = 'Eliminar accion'
        context['list_url'] = self.success_url
        return context

apps/sigma_metas/views/accionestrategica.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import *

from apps.mixins import JefePermissionRequiredMixin
from apps.sigma_metas.forms import AccionEstrategicaForm
from apps.sigma_metas.models import AccionEstrategica

class AccionEstrategicaListView(LoginRequiredMixin,ListView):
    model = AccionEstrategica
    template_name = 'accion_estrategica/accion_estrategica_list.html'
    queryset = AccionEstrategica.objects.all()
    success_url = reverse_lazy('sigma:accion_estrategica_list')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['create_url'] = reverse_lazy('sigma:accion_estrategica_create')
        context['entity'] = 'Accion Estrategica'
        context['title'] = 'Listado de las acciones estrategicas'
        return context

class AccionEstrategicaCreateView(JefePermissionRequiredMixin,LoginRequiredMixin,CreateView):
    model = AccionEstrategica
    template_name = 'form.html'
    form_class = AccionEstrategicaForm
    success_url = reverse_lazy('sigma:accion_estrategica_list')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['create_url'] = reverse_lazy('sigma:accion_estrategica_create')
        context['entity'] = 'Accion Estrategica'
        context['title'] = 'Crear una accion estrategica'
        context['list_url'] = self.success_url
        return context


class AccionEstrategicaUpdateView(JefePermissionRequiredMixin,LoginRequiredMixin,UpdateView):
    model = AccionEstrategica
    template_name = 'form.html'
    form_class = AccionEstrategicaForm
    success_url = reverse_lazy('sigma:accion_estrategica_list')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['create_url'] = reverse_lazy('sigma:accion_estrategica_create')
        context['entity'] = 'Accion Estrategica'
        context['title'] = 'Actualizar una accion estrategica'
        context['list_url'] = self.success_url
        return context


class AccionEstrategicaDeleteView(JefePermissionRequiredMixin,LoginRequiredMixin,DeleteView):
    model = AccionEstrategica
    template_name = 'delete.html'
    success_url = reverse_lazy('sigma:accion_estrategica_list')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['create_url'] = reverse_lazy('sigma:accion_estrategica_create')
        context['entity'] = 'Accion Estrategica'
        context['title'] = 'Eliminar una accion estrategica'
        context['list_url'] = self.success_url
        return context

apps/sigma_metas/views/areapriorizada.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import *

from apps.mixins import JefePermissionRequiredMixin
from apps.sigma_metas.forms import AreaPriorizadaForm
from apps.sigma_metas.models import AreaPriorizada

class AreaPriorizadaListView(LoginRequiredMixin,ListView):
    model = AreaPriorizada
    template_name = 'area/area_list.html'
    queryset = AreaPriorizada.objects.all()
    success_url = reverse_lazy('sigma:area_list')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['create_url'] = reverse_lazy('sigma:area_create')
        context['entity'] = 'Area Priorizada'
        context['title'] = 'Listado de las areas priorizadas'
        return context

class AreaPriorizadaCreateView(JefePermissionRequiredMixin,LoginRequiredMixin,CreateView):
    model = AreaPriorizada
    template_name = 'form.html'
    form_class = AreaPriorizadaForm
    success_url = reverse_lazy('sigma:area_list')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['create_url'] = reverse_lazy('sigma:area_create')
        context['entity'] = 'Area Priorizada'
        context['title'] = 'Crear un area priorizada'
        context['list_url'] = self.success_url
        return context


class AreaPriorizadaUpdateView(JefePermissionRequiredMixin,LoginRequiredMixin,UpdateView):
    model = AreaPriorizada
    template_name = 'form.html'
    form_class = AreaPriorizadaForm
    success_url = reverse_lazy('sigma:area_list')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['create_url'] = reverse_lazy('sigma:area_create')
        context['entity'] = 'Area Priorizada'
        context['title'] = 'Actualizar un area priorizada'
        context['list_url'] = self.success_url
        return context


class AreaPriorizadaDeleteView(JefePermissionRequiredMixin,LoginRequiredMixin,DeleteView):
    model = AreaPriorizada
    template_name = 'delete.html'
    success_url = reverse_lazy('sigma:area_list')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['create_url'] = reverse_lazy('sigma:area_create')
        context['entity'] = 'Area Priorizada'
        context['title'] = 'Eliminar area priorizada'
        context['list_url'] = self.success_url
        return context

apps/sigma_metas/templates/reporte.html
{% extends 'base_list.html' %}
{% load static %}

{% block search %}
    <div class="portlet light row">
        <div class="portlet-title col-12 col-md-8">
            <div class="caption"> {{ area }}</div>
        </div>
        <div class="portlet-body col-md-4 col-12">
            <form class="form container-fluid" id="form-filter" role="form" method="get" action=""
                  enctype="multipart/form-data">
                {% csrf_token %}
                <div class="form-group">
                    {#                                                {{ filter.form.area_id }}#}
                    <div class="input-group">
                        <select class="custom-select custom-select-sm" id="id_area_id" name="area_id">
                            <option selected>Selecciona un área priorizada</option>
                            {% for foo in all_areas %}
                                <option value="{{ foo.id }}">{{ foo }}</option>
                            {% endfor %}
                        </select>
                        <div class="input-group-append">
                            <button class="btn btn-success btn-sm" type="submit">Generar</button>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
{% endblock %}
{% block columns %}
    <td class="text-center">Acciones realizadas</td>
    <td class="text-center">Acciones aplazadas</td>
    <td class="text-center">Acciones pendientes</td>
{% endblock %}
{% block rows %}

    <tr>
        <td class="text-center">
            {% for foo in estado_realizado %}
                {{ foo }}
                <br>
            {% endfor %}
        </td>
        <td class="text-center">
            {% for foo in estado_aplazado %}
                {{ foo }}
                <br>
            {% endfor %}
        </td>
        <td class="text-center">
            {% for foo in estado_pendiente %}
                {{ foo }}
                <br>
            {% endfor %}
        </td>
    </tr>
{% endblock %}

{% block buttons_list %}
                <div class="card-footer circular-bottom">
                <a href="{% url 'index' %}" class="btn btn-primary btnAdd circular">
                    <i class="mdi mdi-arrow-left-bold"></i> Regresar
                </a>
            </div>
{% endblock %}

apps/sigma_metas/templates/reporte_acciones.html
{% extends 'base_list.html' %}
{% load static %}

{% block search %}
    <div class="portlet light row">
        <div class="portlet-title col-12 col-md-8">
            <div class="caption"> {{ estado }}</div>
        </div>
        <div class="portlet-body col-md-4 col-12">
            <form class="form container-fluid" id="form-filter" role="form" method="get" action=""
                  enctype="multipart/form-data">
                {% csrf_token %}
                <div class="form-group">
                    {#                                                {{ filter.form.area_id }}#}
                    <div class="input-group">
                        <select class="custom-select custom-select-sm" id="id_estado_id" name="estado_id">
                            <option selected>Selecciona un estado</option>
                            <option selected>Realizado</option>
                            <option selected>Aplazado</option>
                            <option selected>Pendiente</option>
                        </select>
                        <div class="input-group-append">
                            <button class="btn btn-success btn-sm" type="submit">Mostrar</button>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
{% endblock %}
{% block columns %}
    <td class="text-center">Presupuesto para desarrollar las acciones</td>
    <td class="text-center">Financiamiento para las acciones</td>
    <td class="text-center">Cumplimiento</td>
{% endblock %}
{% block rows %}

    <tr>
        {% if total_presupuesto > 0 %}
            <td class="text-center">{{ total_presupuesto }}</td>
        {% endif %}
        {% if total_presupuesto > 0 %}
        <td class="text-center">{{ total_financiamiento }}</td>
        {% endif %}
        {% if total_presupuesto > 0 %}
        <td class="text-center">{{ cumplimiento }}%</td>
        {% endif %}
    </tr>
{% endblock %}

{% block buttons_list %}
                <div class="card-footer circular-bottom">
                <a href="{% url 'index' %}" class="btn btn-primary btnAdd circular">
                    <i class="mdi mdi-arrow-left-bold"></i> Regresar
                </a>
            </div>
{% endblock %}