apps/sigma_metas/urls.py
from django.contrib import admin
from django.urls import path
from apps.sigma_metas.views.accion import *
from apps.sigma_metas.views.accionestrategica import *
from apps.sigma_metas.views.areapriorizada import *
from apps.sigma_metas.views.indicador import *
from apps.sigma_metas.views.meta import *
from apps.sigma_metas.views.organismo import *
from apps.sigma_metas.views.plan import *
from apps.sigma_metas.views.tarea import *
from apps.sigma_metas.views.reporte import *

app_name='sigma'

urlpatterns = [
    #accion
    path('accion/list/',AccionListView.as_view(), name='accion_list'),
    path('accion/create/',AccionCreateView.as_view(), name='accion_create'),
    path('accion/update/<int:pk>/',AccionUpdateView.as_view(), name='accion_update'),
    path('accion/delete/<int:pk>/',AccionDeleteView.as_view(), name='accion_delete'),

    # accion estrategica
    path('accion/estrategica/list/', AccionEstrategicaListView.as_view(), name='accion_estrategica_list'),
    path('accion/estrategica/create/', AccionEstrategicaCreateView.as_view(), name='accion_estrategica_create'),
    path('accion/estrategica/update/<int:pk>/', AccionEstrategicaUpdateView.as_view(), name='accion_estrategica_update'),
    path('accion/estrategica/delete/<int:pk>/', AccionEstrategicaDeleteView.as_view(), name='accion_estrategica_delete'),

    # area priorizada
    path('area/list/', AreaPriorizadaListView.as_view(), name='area_list'),
    path('area/create/', AreaPriorizadaCreateView.as_view(), name='area_create'),
    path('area/update/<int:pk>/', AreaPriorizadaUpdateView.as_view(), name='area_update'),
    path('area/delete/<int:pk>/', AreaPriorizadaDeleteView.as_view(), name='area_delete'),

    # indicador
    path('indicador/list/', IndicadorListView.as_view(), name='indicador_list'),
    path('indicador/create/', IndicadorCreateView.as_view(), name='indicador_create'),
    path('indicador/update/<int:pk>/', IndicadorUpdateView.as_view(), name='indicador_update'),
    path('indicador/delete/<int:pk>/', IndicadorDeleteView.as_view(), name='indicador_delete'),

    # meta
    path('meta/list/', MetaListView.as_view(), name='meta_list'),
    path('meta/create/', MetaCreateView.as_view(), name='meta_create'),
    path('meta/update/<int:pk>/', MetaUpdateView.as_view(), name='meta_update'),
    path('meta/delete/<int:pk>/', MetaDeleteView.as_view(), name='meta_delete'),

    # organismo
    path('organismo/list/', OrganismoListView.as_view(), name='organismo_list'),
    path('organismo/create/', OrganismoCreateView.as_view(), name='organismo_create'),
    path('organismo/update/<int:pk>/', OrganismoUpdateView.as_view(), name='organismo_update'),
    path('organismo/delete/<int:pk>/', OrganismoDeleteView.as_view(), name='organismo_delete'),

    # plan
    path('plan/list/', PlanListView.as_view(), name='plan_list'),
    path('plan/create/', PlanCreateView.as_view(), name='plan_create'),
    path('plan/update/<int:pk>/', PlanUpdateView.as_view(), name='plan_update'),
    path('plan/delete/<int:pk>/', PlanDeleteView.as_view(), name='plan_delete'),

    # tarea
    path('tarea/list/', TareaListView.as_view(), name='tarea_list'),
    path('tarea/create/', TareaCreateView.as_view(), name='tarea_create'),
    path('tarea/update/<int:pk>/', TareaUpdateView.as_view(), name='tarea_update'),
    path('tarea/delete/<int:pk>/', TareaDeleteView.as_view(), name='tarea_delete'),

    #reportes
    path('reporte/acciones/', ReporteAccion.as_view(), name='reporte_accion'),
    path('reporte/financiamiento/', Reportefinanciamiento.as_view(), name='reporte_financiamiento'),

]

apps/user/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter

from apps.user.views import *

app_name = 'user'

# router = DefaultRouter()
# router.register(r'users', UserViewSet)

urlpatterns = [
    path('user/list/', UserListView.as_view(), name='user_list'),
    path('user/add/', UserCreateView.as_view(), name='user_add'),
    path('user/update/<int:pk>/', UserUpdateView.as_view(), name='user_update'),
    path('user/delete/<int:pk>/', UserDeleteView.as_view(), name='user_delete'),
    # path('api/', include(router.urls)),
]

sigma/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import LogoutView
from django.conf.urls.static import static
from apps.login.views import *
from apps.sigma_metas.views.index import *
from apps.sigma_metas.views.plan import PlanListView

from sigma import settings
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('apps.sigma_metas.urls')),
    path('', include('apps.user.urls')),
    path('', LoginFormView.as_view(), name='index'),
    path('index/', PlanListView.as_view(), name='index'),
    path('login/', include('apps.login.urls')),
    path('logout/', LogoutView.as_view(), name='logout'),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>{{ title }}</title>

    <link rel="icon" href="{% static 'img/citma_logo.jpeg' %}" type="image/x-icon">
    <!-- Material icons -->
    <link rel="stylesheet" href="{% static 'lib/material-icons/css/icons.min.css' %}">
    <!-- jQuery -->
    <script src="{% static 'lib/jquery/jquery-3.6.0.min.js' %}"></script>
    <!-- Bootstrap -->
    <script src="{% static 'lib/bootstrap-4.6.0-dist/js/bootstrap.bundle.min.js' %}"></script>
    <!-- Theme style -->
    <link rel="stylesheet" href="{% static 'lib/admin-lte3/css/adminlte.min.css' %}">
    <!-- AdminLTE App -->
    <script src="{% static 'lib/admin-lte3/js/adminlte.min.js' %}"></script>
    <!-- sweetAlert -->
    <link rel="stylesheet" href="{% static 'lib/sweetalert2/sweetalert2.min.css' %}">
    <script src="{% static 'lib/sweetalert2/sweetalert2.all.min.js' %}"></script>
    <!-- jquery-confirm -->
    <link rel="stylesheet" href="{% static 'lib/jquery-confirm-v3.3.4/jquery-confirm.min.css' %}">
    <script src="{% static 'lib/jquery-confirm-v3.3.4/jquery-confirm.min.js' %}"></script>
    <!-- Functions -->
    <script src="{% static 'js/function.js' %}"></script>
    <!-- My css -->
    <link rel="stylesheet" href="{% static 'css/mystyle.css' %}">
    <!-- Block head -->
    {% block head %}

    {% endblock %}
</head>
{% block body %}

{% endblock %}
</html>

templates/base_list.html
{% extends 'body.html' %}
{% load widget_tweaks %}
{% load static %}
{% block head %}

    {% comment %}    <link rel="stylesheet" href="{% static 'lib/datatables-1.10.20/css/dataTables.bootstrap4.min.css' %}">
    <link rel="stylesheet"
          href="{% static 'lib/datatables-1.10.20/plugins/responsive-2.2.3/css/responsive.bootstrap.min.css' %}">
    <script src="{% static 'lib/datatables-1.10.20/js/jquery.dataTables.min.js' %}"></script>
    <script src="{% static 'lib/datatables-1.10.20/js/dataTables.bootstrap4.min.js' %}"></script>
    <script src="{% static 'lib/datatables-1.10.20/plugins/responsive-2.2.3/js/dataTables.responsive.min.js' %}"></script>
    <script src="{% static 'lib/datatables-1.10.20/plugins/responsive-2.2.3/js/responsive.bootstrap4.min.js' %}"></script>

    <link rel="stylesheet"
          href="{% static 'lib/datatables-1.10.20/plugins/buttons-1.6.1/css/buttons.bootstrap4.min.css' %}">
    <script src="{% static 'lib/datatables-1.10.20/plugins/buttons-1.6.1/js/dataTables.buttons.min.js' %}"></script>
    <script src="{% static 'lib/datatables-1.10.20/plugins/buttons-1.6.1/js/buttons.bootstrap4.min.js' %}"></script>
    <script src="{% static 'lib/datatables-1.10.20/plugins/buttons-1.6.1/js/buttons.colVis.min.js' %}"></script>
    <script src="{% static 'lib/datatables-1.10.20/plugins/buttons-1.6.1/js/buttons.flash.min.js' %}"></script>
    <script src="{% static 'lib/datatables-1.10.20/plugins/buttons-1.6.1/js/buttons.html5.min.js' %}"></script>
    <script src="{% static 'lib/datatables-1.10.20/plugins/buttons-1.6.1/js/buttons.print.min.js' %}"></script>
    <script src="{% static 'lib/datatables-1.10.20/plugins/pdfmake-0.1.36/pdfmake.min.js' %}"></script>
    <script src="{% static 'lib/datatables-1.10.20/plugins/pdfmake-0.1.36/vfs_fonts.js' %}"></script>
    <script src="{% static 'lib/datatables-1.10.20/plugins/jszip-2.5.0/jszip.min.js' %}"></script>{% endcomment %}

    {% block head_list %}

    {% endblock %}
{% endblock %}

{% block content %}

    <div class="card card-info circular m-0">
        <div class="card-header circular-top">
            <h3 class="card-title">
                <i class="mdi mdi-format-list-bulleted-square mdi-18px"></i>
                {{ title }}
            </h3>
            {% block search %}
                {% comment %}                <div class="card-tools">
                    <div class="input-group input-group-sm" style="width: 150px;">
                        <input id="searchInput" oninput="w3.filterHTML('#listTable', ['.odd', '.even'], this.value)"
                               type="text"
                               name="table_search"
                               class="form-control float-right"
                               placeholder="Search">

                    </div>
                </div>{% endcomment %}
            {% endblock %}
        </div>
        <!-- /.card-header -->
        <div class="card-body table-responsive p-2" style="min-height: 325px;">
            <table id="listTable" class="table  table-striped w3-hoverable-light">
                <thead>
                {% block columns %}

                {% endblock %}

                </thead>
                <tbody id="tbody">

                {% block rows %}

                {% endblock %}

                </tbody>
            </table>
        </div>
        <!-- /.card-body -->
        {% block buttons_list %}
            <div class="card-footer circular-bottom">
                <a href="{{ create_url }}" class="btn btn-primary btnAdd circular">
                    <i class="mdi mdi-plus"></i>  {{ entity }}
                </a>
            </div>
        {% endblock %}

    </div>
    <!-- /.card -->
    {% block modal_form %}
        <!-- Modal Create_Update -->
        {#        {% include 'modal.html' %}#}
    {% endblock %}


{% endblock %}

{% block javascript %}

{% endblock %}

templates/body.html
{% extends 'base.html' %}
{% block body %}
    <body class="hold-transition sidebar-mini layout-fixed">
    <div class="wrapper">
        <!-- Header -->
        {% include 'header.html' %}
        <!-- Sidebar -->
        {% include 'sidebar.html' %}
        <!-- Content -->
        <div class="content-wrapper">
            {% block content_header %}
                <div class="content-header py-2">
                    <div class="container-fluid">
                        <div class="row">
                            <div class="col-sm-6">
                                <h1 class="m-0 text-dark pl-lg-5">
                                    <small></small></h1>
                            </div>
                            <div class="col-sm-6">
                                <ol class="breadcrumb float-sm-right pr-lg-5">
                                    <li class="breadcrumb-item"><a href="{% url 'index' %}">Inicio</a></li>
                                    <li class="breadcrumb-item"><a href="{{ list_url }}">{{ entity }}</a></li>
                                </ol>
                            </div>
                        </div>
                    </div>
                </div>
            {% endblock %}
            <div class="content px-0">
                <div class="container-fluid px-lg-5">
                    {% block content %}

                    {% endblock %}
                </div>
            </div>
        </div>
        <!-- Footer -->
        {% include 'footer.html' %}
    </div>
    <!-- Block javascript -->
    {% block javascript %}

    {% endblock %}
    <script>
      {% if messages %}
        let html = `<p>`;
        {% for message in messages %}
          html += `{{ message }}<br>`;
        {% endfor %}
        html += `</p>`;
        Swal.fire({
          title: 'Error',
          html: html,
          icon: 'error'
        });
      {% endif %}
    </script>
    </body>
{% endblock %}

templates/delete.html
{% extends 'body.html' %}
{% load widget_tweaks %}
{% block content %}
    <form method="post" action=".">
        <div class="card card-default circular-top circular-bottom">
            <div class="card-header">
                <h3 class="card-title">
                    <i class="mdi mdi-trash-can-outline"></i>
                    {{ title }}
                </h3>
            </div>
            <div class="card-body circular-bottom">
                {% csrf_token %}
                <input type="hidden" name="action" value="{{ action }}">
                {% if form.errors %}
                    <div class="alert alert-danger alert-dismissible">
                        <button type="button" class="close" data-dismiss="alert" aria-hidden="true"></button>
                        <h5><i class="icon mdi mdi-alert-decagram-outline"></i>Ha ocurrido un error al querer guardar el registro</h5>
                        <ul>
                            {% for field in form %}
                                {% for error in field.errors %}
                                    <li>{{ error }}</li>
                                {% endfor %}
                            {% endfor %}
                        </ul>
                    </div>
                {% endif %}
                <div class="alert alert-warning alert-dismissible circular">
                    <h5><i class="icon mdi mdi-alert-decagram-outline"></i>Cuidado!</h5>
                    Estás seguro de eliminar el registro <b>{{ object }}</b>?
                </div>
            </div>
            <div class="card-footer circular-bottom">
                <button type="submit" class="btn btn-danger circular">
                    <i class="mdi mdi-content-save"></i> Sí, aceptar
                </button>
                <a href="{{ list_url }}" class="btn btn-primary circular">
                    <i class="mdi mdi-cancel"></i> Cancelar
                </a>
            </div>
        </div>
    </form>
    <script>
{% comment %}      $('form').on('submit', function (e) {
        e.preventDefault();
        let parameters = new FormData(this);
        submit_with_ajax(window.location.pathname, 'Notificacion',
          'Estas seguro de eliminar el siguiente registro?', parameters, () => {
            Swal.fire({
              title: 'Alerta',
              html: 'Registro eliminado correcta mente',
              icon: 'success',
              timer: 2000,
              onClose: () => {
                location.href = '{{ list_url }}'
              }
            })
          })
      });{% endcomment %}
    </script>

{% endblock %}

templates/footer.html
{% load static %}
<!-- Main Footer -->
<footer class="main-footer p-2 text-center user-select-none">
    <strong>Desarrollado &copy; <span id="year"></span></strong>
    <strong><a href="#">Darián Andrés Ballagas Almeida ™</a></strong>
    <br>
    Universidad de Camagüey “Ignacio Agramonte y Loynaz”
    <br>
    Facultad de Informática y Ciencias Exactas
</footer>
<script>
  if (new Date().getFullYear() === 2022)
    document.getElementById('year').innerHTML = `2022`
  else
    document.getElementById('year').innerHTML = `2022-${new Date().getFullYear()}`
</script>

templates/form.html
{% extends 'body.html' %}
{% load widget_tweaks %}
{% block head %}
    {% block head_form %}

    {% endblock %}
{% endblock %}
{% block content %}
    <form method="post" action="." enctype="multipart/form-data">
        <div class="card card-info circular">
            <div class="card-header circular-top">
                <h3 class="card-title">
                    {% if action == 'add' %}
                        <i class="mdi mdi-plus"></i>
                    {% else %}
                        <i class="mdi mdi-square-edit-outline"></i>
                    {% endif %}

                    {{ title }}
                </h3>
            </div>
            <div class="card-body">
                {% csrf_token %}

                <input type="hidden" name="action" value="{{ action }}">
                {% if form.errors %}
                    <div class="alert alert-danger circular alert-dismissible">
                        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">x</button>
                        <h5><i class="icon mdi mdi-content-save-settings"></i>Ha ocurrido un error al querer guardar el
                            registro</h5>
                        <ul>
                            {% for field in form %}
                                {% for error in field.errors %}
                                    <li>{{ error }}</li>
                                {% endfor %}
                            {% endfor %}
                        </ul>
                    </div>
                {% endif %}
            {% block campos %}
                {% for field in form.visible_fields %}
                    <div class="form-group row">
                        <label for="asd" class="col-sm-2 col-form-label">{{ field.label }}:</label>
                        <div class="col-sm-10">
                            {{ field|add_class:'form-control circular'|attr:'autocomplete:off' }}
                        </div>
                    </div>
                {% endfor %}
                {% endblock %}
            </div>
            <div class="card-footer circular-bottom">
                <button type="submit" href="{{ list_url }}" class="btn bg-gradient-primary circular">
                    <i class="mdi mdi-content-save"></i> Guardar {{ entity }}
                </button>
{#                <a href="#" class="btn bg-gradient-danger circular">#}
                <a href="{{ list_url }}" class="btn bg-gradient-danger circular">
                    <i class="mdi mdi-cancel"></i> Cancelar
                </a>
            </div>
        </div>
    </form>
    <script>
      {% if form.errors %}
        let errors = '';
        {% for field in form %}
          {% for error in field.errors %}
            errors += '{{ error }}\n';
          {% endfor %}
        {% endfor %}
        {% for error in form.non_field_errors %}
          errors += '{{ error }}\n';
        {% endfor %}

        Swal.fire({
          title: 'Error',
          text: errors,
          icon: 'error'
        });
      {% endif %}

      {% comment %}      $('form').on('submit', function (e) {
              e.preventDefault();
              let parameters = new FormData(this)
              submit_with_ajax_alert(window.location.pathname, 'Notification', 'Are you sure?', parameters, () =>
                location.href = '{{ list_url }}', 'mdi mdi-cancel')
            }){% endcomment %}
    </script>
{% endblock %}

templates/header.html
<nav class="main-header navbar navbar-expand navbar-dark navbar-primary" id="header">
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="mdi mdi-menu mdi-18px"></i></a>
        </li>
        {% comment %}        <li>
            <a class="nav-link pl-0 cursor-pointer" data-toggle="modal" data-target="#links"
               role="button">
                <i class="mdi mdi-link-variant mdi-18px"></i></a>
        </li>{% endcomment %}
        <li class="nav-item">
            <a href="{% url 'index' %}" class="nav-link pl-0"><i
                    class="mdi mdi-home d-sm-inline-block pl-0 pr-0"></i>
                <span class=" d-none d-sm-inline-block"> Inicio</span>
            </a>
        </li>
    </ul>
    <ul class="navbar-nav ml-auto">
        <li class="nav-item">
            {% if request.user.is_authenticated %}
                <a class="nav-link" href="{% url 'logout' %}">
                    <i class="mdi mdi-power" aria-hidden="true"></i>
                Cerrar sesión
                </a>
            {% else %}
                <a class="nav-link" href="{% url 'login' %}">
                    <i class="mdi mdi-login" aria-hidden="true"></i>
                Iniciar sesión
                </a>
            {% endif %}
        </li>
    </ul>
</nav>

templates/sidebar.html
{% load static %}
<aside class="main-sidebar sidebar-light-primary elevation-4">
    <a href="#" class="brand-link">
        <img src="{% static 'img/citma_logo.jpeg' %}"
             alt="AdminLTE Logo"
             class="brand-image img-circle"
             style="opacity: .8">
        <span class="brand-text font-weight-light">CITMA: Tarea vida</span>
    </a>
    <div class="sidebar">
        {% if request.user.is_authenticated %}
            <div class="user-panel py-2  d-flex">
                <div class="image">
                    <img src="{% if request.user.get_image %}{{ request.user.get_image }}
                            {% else %}{% static 'img/user2.png' %}{% endif %}"
                         class="img-circle elevation-2" alt="User Image">
                </div>
                <div class="info">
                    <a href="#" class="d-block">{{ request.user.username }}</a>
                    {#                <a href="{% url 'templates' %}" class="d-block">{{ request.user.username }}</a>#}
                </div>
            </div>
            <div class="rayita-light"></div>
            <nav class="mt-2">
                <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu"
                    data-accordion="false">
                    {% if request.user.role == 'jefe_proyecto' %}
                        <li class="nav-header" >Reportes</li>

                        <li class="nav-item" >
                            <a href="{% url 'sigma:reporte_accion' %}" class="nav-link incidencia-sidebar">
                                <i class="nav-icon mdi mdi-file-question "></i>
                                <p>
                                    Reporte de acciones
                                </p>
                            </a>
                        </li>
                        <li class="nav-item" >
                            <a href="{% url 'sigma:reporte_financiamiento' %}" class="nav-link incidencia-sidebar">
                                <i class="nav-icon mdi mdi-file-question "></i>
                                <p>
                                    Reporte de financiamiento
                                </p>
                            </a>
                        </li>
                        <div class="rayita-light"></div>

                    {% endif %}
                    {% if request.user.role == 'admin' %}


                        <li class="nav-header">Gestión de usuarios</li>

                        <li class="nav-item">
                            <a href="{% url 'user:user_list' %}" class="nav-link incidencia-sidebar">
                                <i class="nav-icon mdi mdi-circle "></i>
                                <p>
                                    Usuario
                                </p>
                            </a>
                        </li>
                        <div class="rayita-light"></div>
                    {% endif %}

                    <li class="nav-header" href="{% url 'sigma:plan_list' %}" >Gestión</li>

                    <li class="nav-item">
                        <a href="{% url 'sigma:plan_list' %}" class="nav-link incidencia-sidebar">
                            <i class="nav-icon mdi mdi-circle "></i>
                            <p>
                                Plan
                            </p>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'sigma:accion_estrategica_list' %}" class="nav-link incidencia-sidebar">
                            <i class="nav-icon mdi mdi-circle "></i>
                            <p>
                                Acciones estratégicas
                            </p>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'sigma:tarea_list' %}" class="nav-link incidencia-sidebar">
                            <i class="nav-icon mdi mdi-circle "></i>
                            <p>
                                Tareas
                            </p>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'sigma:meta_list' %}" class="nav-link incidencia-sidebar">
                            <i class="nav-icon mdi mdi-circle "></i>
                            <p>
                                Metas
                            </p>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'sigma:indicador_list' %}" class="nav-link incidencia-sidebar">
                            <i class="nav-icon mdi mdi-circle "></i>
                            <p>
                                Indicadores
                            </p>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'sigma:accion_list' %}" class="nav-link incidencia-sidebar">
                            <i class="nav-icon mdi mdi-circle "></i>
                            <p>
                                Acciones
                            </p>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'sigma:organismo_list' %}" class="nav-link incidencia-sidebar">
                            <i class="nav-icon mdi mdi-circle "></i>
                            <p>
                                Organismos
                            </p>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'sigma:area_list' %}" class="nav-link incidencia-sidebar">
                            <i class="nav-icon mdi mdi-circle "></i>
                            <p>
                            Áreas priorizadas
                            </p>
                        </a>
                    </li>

                </ul>
            </nav>
        {% endif %}
    </div>
</aside>

templates/startpage.html
{% extends 'body.html' %}
{% load static widget_tweaks %}
{% block head %}
{% endblock %}
{% block content_header %}
{% endblock %}
{% block content %}
{% endblock %}